name: Build Komikku APK

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or 'master', whichever is your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Create local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: komikku-release
          path: app/build/outputs/apk/release/app-release.apk
