name: Build Komikku APK

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Create local.properties
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: local.properties
          contents: |
            sdk.dir=/usr/local/lib/android/sdk

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: komikku-release
          path: app/build/outputs/apk/release/app-release.apk
